# Generated by Django 4.1.5 on 2023-02-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_rate_user_alter_rate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='opening_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
