# Generated by Django 4.1.5 on 2023-02-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_item_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='review',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
