# Generated by Django 4.1.5 on 2023-02-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_views'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='views',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='views',
            index_together=set(),
        ),
    ]
