# Generated by Django 4.1.5 on 2023-02-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_views_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='views',
            unique_together={('user', 'item')},
        ),
    ]
