# Generated by Django 4.1.5 on 2023-02-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_views_unique_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='views',
            index_together={('user', 'item')},
        ),
    ]
