# Generated by Django 4.1.5 on 2023-02-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_views_index_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='views',
            unique_together=set(),
        ),
    ]
