# Generated by Django 4.1.5 on 2023-02-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_views_unique_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='views',
            index_together=set(),
        ),
        migrations.AddConstraint(
            model_name='views',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='name of constraint'),
        ),
    ]
