# Generated by Django 4.1.5 on 2023-02-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_views_index_together_views_name of constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='views',
            name='name of constraint',
        ),
    ]
