# Generated by Django 4.1.5 on 2023-02-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_views_name of constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='views',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='name of constraint'),
        ),
    ]
