# Generated by Django 4.1.5 on 2023-02-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_views_name of constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='views',
            name='name of constraint',
        ),
        migrations.AddConstraint(
            model_name='views',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='view'),
        ),
        migrations.AddField(
            model_name='fav',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
        migrations.AddConstraint(
            model_name='fav',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='fav'),
        ),
    ]
