# Generated by Django 4.1.5 on 2023-02-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_fav_fav_fav_fav'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fav',
            name='fav',
        ),
        migrations.AddConstraint(
            model_name='fav',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='fav'),
        ),
    ]
