# Generated by Django 4.1.5 on 2023-02-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_fav_fav_fav_fav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
