# Generated by Django 4.1.5 on 2023-02-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_fav_fav_name of constraint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
