# Generated by Django 4.1.5 on 2023-02-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_favlist_favlist_name of constraint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Views',
        ),
    ]
