# Generated by Django 4.1.5 on 2023-02-16 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_item_gellary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gellary',
        ),
        migrations.CreateModel(
            name='ItemGellary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Item/%y/%m/%d')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
            ],
        ),
    ]
